name = "pesde/tooling"
version = "0.1.0"
private = true

workspace_members = ["toolchainlib", "bins/*"]

[target]
environment = "lune"

[dependencies]
option = { name = "lukadev_0/option", version = "^1.2.0" }
pathfs = { name = "jiwonz/pathfs", version = "^0.1.0" }

[indices]
default = "https://github.com/daimond113/pesde-index"
