name = "pesde/tooling"
version = "0.1.0"
private = true

workspace_members = ["toolchainlib", "bins/*"]

[target]
environment = "lune"

[indices]
default = "https://github.com/daimond113/pesde-index"
