name = "compeydev/lune"
version = "0.8.9"
description = "A standalone Luau runtime"
authors = [
    "CompeyDev <hi@devcomp.xyz>",
    "Filip Tibell <filip.tibell@gmail.com>",
]
repository = "https://github.com/CompeyDev/pesde-tooling/blob/main/lune"
license = "MIT"

[target]
environment = "lune"
bin = "init.luau"

[dependencies]
result = { name = "lukadev_0/result", version = "^1.2.0" }
option = { name = "lukadev_0/option", version = "^1.2.0" }
semver = { name = "0x5eal/semver", version = "^0.1.1", target = "luau" }
core = { workspace = "compeydev/binlib", version = "^" }

[indices]
default = "https://github.com/daimond113/pesde-index"
